name: projekakhirteori
description: "A Vinyl Store Flutter application with location services, timezone features, and event notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  http: ^1.1.0
  sqflite: ^2.3.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  path: ^1.8.3
  sensors_plus: ^4.0.2
  
  # Image handling for profile photos
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Location-based services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Time zone conversion
  timezone: ^0.9.2
  
  # URL launcher for maps, phone, website links
  url_launcher: ^6.2.2
  
  # NEW: Notifications
  flutter_local_notifications: ^17.2.2
  
  # UI Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # You can add assets here if needed
  # assets:
  #   - images/
  #   - assets/